package com.resolveservicos.utils.emailMessage;

import com.resolveservicos.entities.model.User;

public class EmailMessage {

    public static String createTitle(User user) {
        return user.getName() + " seu cadastro foi realizado com sucesso!";
    }

    public static String messageToNewUser(User user, String password) {
        return "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <style>\n"
                + "        .wrapper {\n"
                + "            width: 90%;\n"
                + "            max-width: 600px;\n"
                + "            margin: 20px 0 0 25%;\n"
                + "        }\n"
                + "        header {\n"
                + "            background-color: #333;\n"
                + "            color: white;\n"
                + "            padding: 10px;\n"
                + "            display: flex;\n"
                + "            justify-content: center;\n"
                + "        }\n"
                + "        header img {\n"
                + "            height: 40px;\n"
                + "            width: auto;\n"
                + "        }\n"
                + "        .container {\n"
                + "            background-color: white;\n"
                + "            padding: 20px;\n"
                + "            text-align: left;\n"
                + "        }\n"
                + "        p {\n"
                + "            font-size: 16px;\n"
                + "            line-height: 1.5;\n"
                + "             font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
                + "        }\n"
                + "        footer {\n"
                + "            background-color: #333;\n"
                + "            color: white;\n"
                + "            padding: 10px;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        /* Media Queries */\n"
                + "        @media (max-width: 1241px) {\n"
                + "            .wrapper {\n"
                + "                width: 95%;\n"
                +"                 margin: 20px;\n"
                + "            }\n"
                + "            header img {\n"
                + "                height: 30px;\n"
                + "            }\n"
                + "            p {\n"
                + "                 font-size: 14px;\n"
                + "                 font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body style='background-color: #dbd8d8a0; text-align: left; margin: 0; padding: 0; display: flex; justify-content: center;'>\n"
                + "    <div class=\"wrapper\">\n"
                + "        <header>\n"
                + "            <img src=\"https://uploaddeimagens.com.br/images/004/819/894/full/Resolve_20240802_192808_0000-1-fotor-bg-remover-2024080220148.png?1722639811\" alt=\"Logo Resolve Serviços\">\n"
                + "        </header>\n"
                + "        <div class=\"container\">\n"
                + "            <h1>Olá, <strong> " + user.getName().toUpperCase() + "</strong>!</h1>\n"
                + "            <p>Seja bem-vindo ao Resolve Serviços!</p>\n"
                + "            <p>Estamos muito felizes em ter você conosco. O Resolve Serviços foi criada para ajudar você a resolver todos os problemas de manutenção do seu lar com facilidade e eficiência.</p>\n"
                + "            <p>Aqui está o que você pode fazer agora:</p>\n"
                + "            <ul>\n"
                + "                 <li>Agendar serviços de manutenção com nossos prestadores de serviços confiáveis.</li>\n"
                + "                 <li>Gerenciar seus agendamentos e acompanhar o status dos serviços.</li>\n"
                + "                 <li>Entrar em contato conosco sempre que precisar de ajuda ou tiver alguma dúvida.</li>\n"
                + "            </ul>\n"
                + "            <p>Abaixo estão suas credenciais de acesso para o nosso aplicativo. Aproveite!:</p>\n"
                + "            <p><strong>Usuário:</strong> " + user.getName() + " </p>\n"
                + "            <p><strong>Senha de acesso:</strong> " + password + "</p>\n"
                + "            <p>Se precisar de qualquer assistência, nossa equipe está sempre pronta para ajudar. Basta responder a este e-mail ou acessar nossa central de ajuda através do aplicativo.</p>\n"
                + "            <p>Mais uma vez, bem-vindo ao Resolve Serviços. Estamos ansiosos para ajudar você a manter seu lar em perfeito estado!</p>\n"
                + "            <p>Atenciosamente,</p>\n"
                + "            <p>Equipe Resolve Serviços!</p>\n"
                + "        </div>\n"
                + "        <footer>\n"
                + "            <p>&copy; 2024 Resolve Serviços. Todos os direitos reservados.</p>\n"
                + "        </footer>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
    }
}
